const translate = {
    eng: {
        goods: 'Search for goods...',
        contacts: 'Our Contacts',
        cart: 'My Cart',
        lang: 'Language',
        boardG: 'Board games',
        sort: 'Sort:',
        byName: 'by name',
        puzzles: 'Puzzles',
        gameSeries: 'Game series',
        comicsBooks: 'Comics and books',
        accs: 'Accessories',
        lowToH: 'cheap to expensive',
        highToL: 'expensive to cheap',
        price: 'Price, UAH',
        ukr: 'Ukrainian',
        eng: 'English',
        rus: 'Russian',
        availab: 'Availability',
        inStock: 'In stock',
        notAv: 'Not available',
        new: 'New',
        discount: 'With a discount',
        preOrd: 'Pre-order',
        countOfP: 'Count of players',
        more4: 'More than 4',
        difficulty: 'Difficulty',
        easy: 'Easy',
        medium: 'Medium',
        difficult: 'Difficult',
        uah: 'UAH',
        buy: 'Buy'
    },
    ukr: {
        goods: 'Пошук товарів...',
        contacts: 'Наші контакти',
        cart: 'Мій кошик',
        lang: 'Мова',
        boardG: 'Настільні ігри',
        sort: 'Сортування:',
        byName: 'за назвою',
        puzzles: 'Пазли',
        gameSeries: 'Серії ігор',
        comicsBooks: 'Комікси та книги',
        accs: 'Аксесуари',
        lowToH: 'спочатку дешевше',
        highToL: 'спочатку дорожче',
        price: 'Ціна, грн',
        ukr: 'Українська',
        eng: 'Англійська',
        rus: 'Російська',
        availab: 'Наявність',
        inStock: 'В наявності',
        notAv: 'Немає в наявності',
        new: 'Новинка',
        discount: 'Зі знижкою',
        preOrd: 'Передзамовлення',
        countOfP: 'Кількість гравців',
        more4: 'Понад 4',
        difficulty: 'Складність',
        easy: 'Низька',
        medium: 'Середня',
        difficult: 'Висока',
        uah: 'грн',
        buy: 'Купити'
    }
};

export default translate;