const translate = {
    eng: {
        goods: 'Search for goods...',
        contacts: 'Our Contacts',
        cart: 'My Cart',
        lang: 'Language',
        boardG: 'Board games',
        sort: 'Sort:',
        byName: 'by name',
        puzzles: 'Puzzles',
        gameSeries: 'Game series',
        comicsBooks: 'Comics and books',
        accs: 'Accessories',
        lowToH: 'cheap to expensive',
        highToL: 'expensive to cheap',
        price: 'Price, UAH',
        ukr: 'Ukrainian',
        eng: 'English',
        rus: 'Russian',
        availab: 'Availability',
        inStock: 'In stock',
        notAv: 'Not available',
        new: 'New',
        discount: 'With a discount',
        preOrd: 'Pre-order',
        countOfP: 'Count of players',
        more4: 'More than 4',
        difficulty: 'Difficulty',
        easy: 'Easy',
        medium: 'Medium',
        difficult: 'Difficult',
        uah: 'UAH',
        buy: 'Buy',
        copyright: 'BGS is an online store of board games.',
        rights:'All rights reserved.',
        survey: 'Survey',
        catalog: 'Catalog',
        contactInfo: 'Contact information',
        place:'Morska Prozorist Street, 7-A, 3rd floor, Kyiv',
        // Survey 
        surveyTitle:'Survey for site visitors',
        fName:'First name:',
        email:'Email:',
        siteDesignQ:'How much do you rate the design of the site?',
        whereDYouQ:'Where did you find out about us?',
        whereDYouQ_browser:'By search in the browser.',
        whereDYouQ_advert:'By advertisment.',
        whereDYouQ_relatives:'Acquaintances/friends/relatives told me.',
        whereDYouQ_other:'Other.',
        whichSectionQ:'Which section of the site do you like best?',
        whichSectionQ_boardG:'Board games.',
        whichSectionQ_puzz:'Puzzles.',
        whichSectionQ_gameS:'Game series.',
        whichSectionQ_comics:'Comics and books',
        whichSectionQ_accs:'Accessories.',
        fillUp:'Fill in',
        sendForm:'Send form',
        clearForm:'Clear'
    },
    ukr: {
        goods: 'Пошук товарів...',
        contacts: 'Наші контакти',
        cart: 'Мій кошик',
        lang: 'Мова',
        boardG: 'Настільні ігри',
        sort: 'Сортування:',
        byName: 'за назвою',
        puzzles: 'Пазли',
        gameSeries: 'Серії ігор',
        comicsBooks: 'Комікси та книги',
        accs: 'Аксесуари',
        lowToH: 'спочатку дешевше',
        highToL: 'спочатку дорожче',
        price: 'Ціна, грн',
        ukr: 'Українська',
        eng: 'Англійська',
        rus: 'Російська',
        availab: 'Наявність',
        inStock: 'В наявності',
        notAv: 'Немає в наявності',
        new: 'Новинка',
        discount: 'Зі знижкою',
        preOrd: 'Передзамовлення',
        countOfP: 'Кількість гравців',
        more4: 'Понад 4',
        difficulty: 'Складність',
        easy: 'Низька',
        medium: 'Середня',
        difficult: 'Висока',
        uah: 'грн',
        buy: 'Купити',
        copyright: 'BGS — Інтернет-магазин настільних ігор.',
        rights:'Всі права застережені.',
        survey: 'Опитування',
        catalog: 'Каталог',
        contactInfo: 'Контактна інформація',
        place:'Морська Прозорість вулиця, 7-А, 3-ий поверх, Київ',
        // Опрос
        surveyTitle:'Опитування для відвідувачів сайту',
        fName:"Ім'я:",
        email:'Електронна пошта:',
        siteDesignQ:'Наскільки ви оцінюєте дизайн сайту?',
        whereDYouQ:'Де ви дізналися про нас?',
        whereDYouQ_browser:'За пошуком у браузері.',
        whereDYouQ_advert:'У рекламі.',
        whereDYouQ_relatives:'Мені розповіли знайомі/друзі/родичі.',
        whereDYouQ_other:'Інше.',
        whichSectionQ:'Який розділ сайту вам подобається більше?',
        whichSectionQ_boardG:'Настільні ігри.',
        whichSectionQ_puzz:'Пазли.',
        whichSectionQ_gameS:'Серії ігор.',
        whichSectionQ_accs:'Аксесуари.',
        fillUp:'Заповнити',
        sendForm:'Відправити',
        clearForm:'Очистити'
    }
};

export default translate;